In [1]:
# load libraries
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn import preprocessing
from sklearn.metrics import confusion_matrix, classification_report
import matplotlib.pyplot as plt

In [2]:
dataStreamPath = 'C:\\Users\\PRECISION 7X10\\Documents\\OLGA_pytorch\\'#modify this with your path
graphsStreamPath='C:\\Users\\PRECISION 7X10\\Documents\\OLGA_pytorch\\graphs_all2\\'#modify this with your path
shapvaluesStreamPath='C:\\Users\\PRECISION 7X10\\Documents\\OLGA_pytorch\\shapvalues_all2\\'#modify this with your path

In [3]:
# load data 
df_train = pd.read_csv(dataStreamPath + "df_train.csv")
df_test = pd.read_csv(dataStreamPath + "df_test.csv")

In [4]:
df_train.shape
#df_test.shape

(12179375, 105)

In [88]:
df_all = pd.concat([df_train,df_test])


pcm_LOGenergy_sma   pcm_zcr_sma  voiceprob_sma        f0_sma  \
count       1.623916e+07  1.623916e+07   1.623916e+07  1.623916e+07   
mean       -1.888414e+01  2.916988e-01   3.788241e-01  5.625996e+01   
std         9.494387e+00  3.016677e-01   2.387724e-01  1.013307e+02   
min        -4.158871e+01  0.000000e+00   0.000000e+00  0.000000e+00   
25%        -2.003430e+01  1.000000e-01   2.299332e-01  0.000000e+00   
50%        -1.633344e+01  1.666667e-01   3.322144e-01  0.000000e+00   
75%        -1.312681e+01  3.316667e-01   5.526084e-01  8.333333e+01   
max         2.000000e+00  2.000000e+00   2.000000e+00  4.705882e+02   

          f0env_sma  pcm_fftMag_fband0-250_sma  pcm_fftMag_fband0-650_sma  \
count  1.623916e+07               1.623916e+07               1.623916e+07   
mean   1.942670e+02               2.525414e-04               3.262605e-03   
std    1.118042e+02               8.002975e-03               7.061946e-02   
min    0.000000e+00               0.000000e+00               0.000000e+00   
25%    1.496089e+02               5.521949e-09               2.855959e-08   
50%    2.048964e+02               1.598195e-07               2.068128e-06   
75%    2.565421e+02               7.608498e-06               9.412382e-05   
max    4.705782e+02               2.000000e+00               7.960482e+00   

       pcm_fftMag_spectralRollOff25_0_sma  pcm_fftMag_spectralRollOff50_0_sma  \
count                        1.623916e+07                        1.623916e+07   
mean                         9.659552e+02                        1.380341e+03   
std                          7.896358e+02                        9.847405e+02   
min                          0.000000e+00                        0.000000e+00   
25%                          3.541667e+02                        4.895833e+02   
50%                          7.395833e+02                        1.302083e+03   
75%                          1.520833e+03                        2.218750e+03   
max                          3.968750e+03                        4.000000e+03   

       pcm_fftMag_spectralRollOff75_0_sma  ...  pcm_fftMag_mfcc_3_  \
count                        1.623916e+07  ...        1.623916e+07   
mean                         1.859204e+03  ...       -1.300555e+01   
std                          1.137648e+03  ...        1.839031e+01   
min                          0.000000e+00  ...       -1.253905e+02   
25%                          8.645833e+02  ...       -2.419952e+01   
50%                          2.010417e+03  ...       -9.152401e+00   
75%                          2.854167e+03  ...        0.000000e+00   
max                          4.000000e+03  ...        8.876147e+01   

       pcm_fftMag_mfcc_4_  pcm_fftMag_mfcc_5_  pcm_fftMag_mfcc_6_  \
count        1.623916e+07        1.623916e+07        1.623916e+07   
mean        -7.252221e+00       -6.518470e+00       -1.464681e+00   
std          1.569242e+01        1.608184e+01        1.545418e+01   
min         -1.149150e+02       -1.138947e+02       -1.262873e+02   
25%         -1.667023e+01       -1.605942e+01       -1.009016e+01   
50%         -4.073590e+00       -3.783020e+00        0.000000e+00   
75%          1.272074e+00        1.944761e+00        6.543562e+00   
max          8.709324e+01        1.059340e+02        1.065877e+02   

       pcm_fftMag_mfcc_7_  pcm_fftMag_mfcc_8_  pcm_fftMag_mfcc_9_  \
count        1.623916e+07        1.623916e+07        1.623916e+07   
mean        -6.195182e+00       -2.275914e+00       -4.712354e+00   
std          1.650002e+01        1.476115e+01        1.417317e+01   
min         -1.152227e+02       -1.040993e+02       -1.073226e+02   
25%         -1.589032e+01       -1.064943e+01       -1.306325e+01   
50%         -3.850446e+00        0.000000e+00       -2.475908e+00   
75%          1.803184e+00        5.373746e+00        2.549448e+00   
max          1.134609e+02        1.136429e+02        1.074227e+02   

       pcm_fftMag_mfcc_10_  pcm_fftMag_mfcc_11_  pcm_fftMag_mfcc_12_

In [90]:
stats = df_all.iloc[:,5:91].describe()

In [92]:
stats.transpose().to_csv("targetdata_statistics.csv")


In [95]:
del df_all

In [5]:
X_train = df_train.iloc[:, 5:91]
X_train

pcm_LOGenergy_sma  pcm_zcr_sma  voiceprob_sma  f0_sma  f0env_sma  \
0                   0.00000     0.000000       0.000000     0.0     0.0000   
1                 -23.28713     0.723333       0.217301     0.0   164.9366   
2                 -23.42141     0.713333       0.196045     0.0   164.9366   
3                 -22.89489     0.643333       0.197920     0.0   164.9366   
4                 -22.77770     0.725000       0.269155     0.0   164.9366   
...                     ...          ...            ...     ...        ...   
12179370          -41.58871     0.990000       0.000000     0.0     0.0000   
12179371          -41.58871     0.990000       0.000000     0.0     0.0000   
12179372          -41.58871     0.990000       0.000000     0.0     0.0000   
12179373          -41.58871     0.990000       0.000000     0.0     0.0000   
12179374          -41.58871     0.990000       0.000000     0.0     0.0000   

          pcm_fftMag_fband0-250_sma  pcm_fftMag_fband0-650_sma  \
0                      0.000000e+00               0.000000e+00   
1                      3.094790e-11               2.386891e-10   
2                      6.110110e-11               2.690444e-10   
3                      8.974540e-11               3.249551e-10   
4                      6.143090e-11               3.950181e-10   
...                             ...                        ...   
12179370               0.000000e+00               0.000000e+00   
12179371               0.000000e+00               0.000000e+00   
12179372               0.000000e+00               0.000000e+00   
12179373               0.000000e+00               0.000000e+00   
12179374               0.000000e+00               0.000000e+00   

          pcm_fftMag_spectralRollOff25_0_sma  \
0                                      0.000   
1                                   1937.500   
2                                   2072.917   
3                                   2395.833   
4                                   2489.583   
...                                      ...   
12179370                              31.250   
12179371                              31.250   
12179372                              31.250   
12179373                              31.250   
12179374                              31.250   

          pcm_fftMag_spectralRollOff50_0_sma  \
0                                      0.000   
1                                   2666.667   
2                                   2729.167   
3                                   3145.833   
4                                   3375.000   
...                                      ...   
12179370                              31.250   
12179371                              31.250   
12179372                              31.250   
12179373                              31.250   
12179374                              31.250   

          pcm_fftMag_spectralRollOff75_0_sma  ...  pcm_fftMag_mfcc_3_  \
0                                      0.000  ...            0.000000   
1                                   3562.500  ...           -6.729422   
2                                   3552.083  ...           -7.343003   
3                                   3645.833  ...           -7.586257   
4                                   3635.417  ...            5.355905   
...                                      ...  ...                 ...   
12179370                              31.250  ...            0.000000   
12179371                              31.250  ...            0.000000   
12179372                              31.250  ...            0.000000   
12179373                              31.250  ...            0.000000   
12179374                              31.250  ...            0.000000   

          pcm_fftMag_mfcc_4_  pcm_fftMag_mfcc_5_  pcm_fftMag_mfcc_6_  \
0                   0.000000            0.000000            0.000000   
1                   0.411122           14.940340           -7.770701   
2                 -11.013250     

In [6]:
y_train_symptoms = df_train.iloc[:, 94:104]
y_train_symptoms

anxiety  decreased_activity  decreased_mood  disorganization  \
0               3                   0               1               10   
1               3                   0               1               10   
2               3                   0               1               10   
3               3                   0               1               10   
4               3                   0               1               10   
...           ...                 ...             ...              ...   
12179370        0                   0               0                1   
12179371        0                   0               0                1   
12179372        0                   0               0                1   
12179373        0                   0               0                1   
12179374        0                   0               0                1   

          elevated_activity  elevated_mood  irritability  sleep_disorder  \
0                         9              3             8              10   
1                         9              3             8              10   
2                         9              3             8              10   
3                         9              3             8              10   
4                         9              3             8              10   
...                     ...            ...           ...             ...   
12179370                  1              2             2               3   
12179371                  1              2             2               3   
12179372                  1              2             2               3   
12179373                  1              2             2               3   
12179374                  1              2             2               3   

          somatisation  suicide  
0                    0        0  
1                    0        0  
2                    0        0  
3                    0        0  
4                    0        0  
...                ...      ...  
12179370             0        0  
12179371             0        0  
12179372             0        0  
12179373             0        0  
12179374             0        0  

[12179375 rows x 10 columns]

In [7]:
y_train_states = df_train.iloc[:, 1]
y_train_states

0           mixed
1           mixed
2           mixed
3           mixed
4           mixed
            ...  
12179370    mania
12179371    mania
12179372    mania
12179373    mania
12179374    mania
Name: hamd_ymrs, Length: 12179375, dtype: object

In [8]:
y_train_states.value_counts()

depression    5194926
euthymia      3649643
mixed         3088107
mania          246699
Name: hamd_ymrs, dtype: int64

In [9]:
# from categorical to numeric target
le = preprocessing.LabelEncoder()
le.fit(y_train_states.values.ravel())
y_train_states_encoded = le.transform(y_train_states.values.ravel())
y_train_states_encoded

array([3, 3, 3, ..., 2, 2, 2])

In [10]:
df_test

Unnamed: 0         day hamd_ymrs  visit_number  \
0                 2  2018-03-21     mixed             2   
1                 3  2018-03-21     mixed             2   
2                 4  2018-03-21     mixed             2   
3                 5  2018-03-21     mixed             2   
4                 6  2018-03-21     mixed             2   
...             ...         ...       ...           ...   
4059775      945574  2018-08-22     mania             5   
4059776      945575  2018-08-22     mania             5   
4059777      945576  2018-08-22     mania             5   
4059778      945577  2018-08-22     mania             5   
4059779      945578  2018-08-22     mania             5   

         dw_mobilerecording_id  frame_nr  pcm_LOGenergy_sma  pcm_zcr_sma  \
0                       5858.0     692.0          -22.36474     0.638333   
1                       5858.0     690.0          -23.57593     0.861667   
2                       5858.0     683.0          -24.43365     0.875000   
3                       5858.0     678.0          -24.06601     0.875000   
4                       5858.0     675.0          -23.45980     0.853333   
...                        ...       ...                ...          ...   
4059775                26537.0      17.0          -41.58871     0.990000   
4059776                26537.0       6.0          -41.58871     0.990000   
4059777                26537.0       5.0          -41.58871     0.990000   
4059778                26537.0       4.0          -41.58871     0.990000   
4059779                26537.0       1.0          -41.58871     0.990000   

         voiceprob_sma  f0_sma  ...  decreased_activity  decreased_mood  \
0             0.242282     0.0  ...                   0               1   
1             0.301797     0.0  ...                   0               1   
2             0.191910     0.0  ...                   0               1   
3             0.241135     0.0  ...                   0               1   
4             0.201962     0.0  ...                   0               1   
...                ...     ...  ...                 ...             ...   
4059775       0.000000     0.0  ...                   0               0   
4059776       0.000000     0.0  ...                   0               0   
4059777       0.000000     0.0  ...                   0               0   
4059778       0.000000     0.0  ...                   0               0   
4059779       0.000000     0.0  ...                   0               0   

         disorganization  elevated_activity  elevated_mood  irritability  \
0                     10                  9              3             8   
1                     10                  9              3             8   
2                     10                  9              3             8   
3                     10                  9              3             8   
4                     10                  9              3             8   
...                  ...                ...            ...           ...   
4059775                1                  1              2             2   
4059776                1                  1              2             2   
4059777                1                  1              2             2   
4059778                1                  1              2             2   
4059779                1                  1              2             2   

         sleep_disorder  somatisation  suicide  is_day_of_visit  
0                    10             0        0            False  
1                    10             0        0            False  
2                    10             0        0            False  
3                    10             0        0            False  
4                    10             0        0            False  
...                 ...           ...      ...              ...  
4059775               3             0        0            False  
4059776               3             0        

In [11]:
X_test = df_test.iloc[:, 6:92]
X_test

pcm_LOGenergy_sma  pcm_zcr_sma  voiceprob_sma  f0_sma  f0env_sma  \
0                -22.36474     0.638333       0.242282     0.0   164.9366   
1                -23.57593     0.861667       0.301797     0.0   164.9366   
2                -24.43365     0.875000       0.191910     0.0   164.9366   
3                -24.06601     0.875000       0.241135     0.0   164.9366   
4                -23.45980     0.853333       0.201962     0.0   164.9366   
...                    ...          ...            ...     ...        ...   
4059775          -41.58871     0.990000       0.000000     0.0     0.0000   
4059776          -41.58871     0.990000       0.000000     0.0     0.0000   
4059777          -41.58871     0.990000       0.000000     0.0     0.0000   
4059778          -41.58871     0.990000       0.000000     0.0     0.0000   
4059779          -41.58871     0.990000       0.000000     0.0     0.0000   

         pcm_fftMag_fband0-250_sma  pcm_fftMag_fband0-650_sma  \
0                     1.062678e-10               5.327571e-10   
1                     2.550390e-11               3.021475e-10   
2                     6.719860e-11               2.484317e-10   
3                     3.958790e-11               2.698097e-10   
4                     3.057900e-11               2.294124e-10   
...                            ...                        ...   
4059775               0.000000e+00               0.000000e+00   
4059776               0.000000e+00               0.000000e+00   
4059777               0.000000e+00               0.000000e+00   
4059778               0.000000e+00               0.000000e+00   
4059779               0.000000e+00               0.000000e+00   

         pcm_fftMag_spectralRollOff25_0_sma  \
0                                  2541.667   
1                                  2270.833   
2                                  1666.667   
3                                  1854.167   
4                                  1958.333   
...                                     ...   
4059775                              31.250   
4059776                              31.250   
4059777                              31.250   
4059778                              31.250   
4059779                              31.250   

         pcm_fftMag_spectralRollOff50_0_sma  \
0                                  3385.417   
1                                  3145.833   
2                                  2364.583   
3                                  2583.333   
4                                  2312.500   
...                                     ...   
4059775                              31.250   
4059776                              31.250   
4059777                              31.250   
4059778                              31.250   
4059779                              31.250   

         pcm_fftMag_spectralRollOff75_0_sma  ...  pcm_fftMag_mfcc_3_  \
0                                  3708.333  ...           -6.305238   
1                                  3552.083  ...           -8.821964   
2                                  3114.583  ...          -15.958660   
3                                  3333.333  ...           -5.791925   
4                                  2875.000  ...           -1.845119   
...                                     ...  ...                 ...   
4059775                              31.250  ...            0.000000   
4059776                              31.250  ...            0.000000   
4059777                              31.250  ...            0.000000   
4059778                              31.250  ...            0.000000   
4059779                              31.250  ...            0.000000   

         pcm_fftMag_mfcc_4_  pcm_fftMag_mfcc_5_  pcm_fftMag_mfcc_6_  \
0                 -4.126776           -0.756497            0.591379   
1                -22.266800            4.711215           18.435010   
2                -12.099890           11.508420           -7.042534   
3                 -1.767

In [12]:
y_test_symptoms = df_test.iloc[:, 95:105]
y_test_symptoms

anxiety  decreased_activity  decreased_mood  disorganization  \
0              3                   0               1               10   
1              3                   0               1               10   
2              3                   0               1               10   
3              3                   0               1               10   
4              3                   0               1               10   
...          ...                 ...             ...              ...   
4059775        0                   0               0                1   
4059776        0                   0               0                1   
4059777        0                   0               0                1   
4059778        0                   0               0                1   
4059779        0                   0               0                1   

         elevated_activity  elevated_mood  irritability  sleep_disorder  \
0                        9              3             8              10   
1                        9              3             8              10   
2                        9              3             8              10   
3                        9              3             8              10   
4                        9              3             8              10   
...                    ...            ...           ...             ...   
4059775                  1              2             2               3   
4059776                  1              2             2               3   
4059777                  1              2             2               3   
4059778                  1              2             2               3   
4059779                  1              2             2               3   

         somatisation  suicide  
0                   0        0  
1                   0        0  
2                   0        0  
3                   0        0  
4                   0        0  
...               ...      ...  
4059775             0        0  
4059776             0        0  
4059777             0        0  
4059778             0        0  
4059779             0        0  

[4059780 rows x 10 columns]

In [13]:
y_test_states = df_test.iloc[:, 2]
y_test_states

0          mixed
1          mixed
2          mixed
3          mixed
4          mixed
           ...  
4059775    mania
4059776    mania
4059777    mania
4059778    mania
4059779    mania
Name: hamd_ymrs, Length: 4059780, dtype: object

In [14]:
y_test_states.value_counts()

depression    1731639
euthymia      1216541
mixed         1029368
mania           82232
Name: hamd_ymrs, dtype: int64

In [15]:
y_test_states_encoded = le.transform(y_test_states.values.ravel())
y_test_states_encoded

array([3, 3, 3, ..., 2, 2, 2])

In [16]:
# standardize data
scaler = preprocessing.StandardScaler()
scaler.fit(X_train.values)
X_train_scaled = scaler.transform(X_train.values)
X_train_scaled

array([[ 1.98907251, -0.96696294, -1.58623226, ...,  0.25019649,
         0.23997193, -1.89742156],
       [-0.46345144,  1.43047451, -0.67623924, ...,  0.04909636,
         0.05111859, -1.18910075],
       [-0.47759337,  1.39733021, -0.76525193, ..., -0.87487645,
        -0.05573946, -1.33832562],
       ...,
       [-2.39091367,  2.31432257, -1.58623226, ...,  0.25019649,
         0.23997193, -1.89742156],
       [-2.39091367,  2.31432257, -1.58623226, ...,  0.25019649,
         0.23997193, -1.89742156],
       [-2.39091367,  2.31432257, -1.58623226, ...,  0.25019649,
         0.23997193, -1.89742156]])

In [17]:
X_test_scaled = scaler.transform(X_test.values)
X_test_scaled

array([[-0.36630836,  1.14874798, -0.57162523, ..., -0.02493272,
         0.13336583, -1.21966264],
       [-0.49386691,  1.88897085, -0.32239329, ...,  0.47575996,
         1.41900843, -1.03720569],
       [-0.58419916,  1.93316314, -0.78257021, ...,  0.28102691,
        -0.2001199 , -1.40960576],
       ...,
       [-2.39091367,  2.31432257, -1.58623226, ...,  0.25019649,
         0.23997193, -1.89742156],
       [-2.39091367,  2.31432257, -1.58623226, ...,  0.25019649,
         0.23997193, -1.89742156],
       [-2.39091367,  2.31432257, -1.58623226, ...,  0.25019649,
         0.23997193, -1.89742156]])

# NEURAL NETWORK

## One head

In [18]:
model_name='one_head'

In [19]:
# one-head multioutput model
input = tf.keras.layers.Input(shape=(86,), name='input')
hidden = tf.keras.layers.Dense(64, activation='relu', name='dense')(input)
dropout = tf.keras.layers.Dropout(0.2, name='dropout')(hidden)
symptom_output = tf.keras.layers.Dense(10, name='symptom_output')(dropout)
state_output = tf.keras.layers.Dense(4, activation='softmax', name='state_output')(symptom_output)

one_head = tf.keras.Model(inputs=input, 
                          outputs=[symptom_output, state_output], 
                          name='one-head-model')

In [20]:
one_head.summary()

Model: "one-head-model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input (InputLayer)          [(None, 86)]              0         
                                                                 
 dense (Dense)               (None, 64)                5568      
                                                                 
 dropout (Dropout)           (None, 64)                0         
                                                                 
 symptom_output (Dense)      (None, 10)                650       
                                                                 
 state_output (Dense)        (None, 4)                 44        
                                                                 
Total params: 6,262
Trainable params: 6,262
Non-trainable params: 0
_________________________________________________________________


In [21]:
one_head.compile(optimizer='adam',
                 loss=[tf.keras.losses.MeanAbsoluteError(),
                       tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False)],
                 loss_weights=[0.5, 0.5],
                 metrics=['mae', 'accuracy'])

In [22]:
early_stopping = tf.keras.callbacks.EarlyStopping(monitor='state_output_accuracy', patience=3)

In [23]:
one_head.fit(X_train_scaled, [y_train_symptoms, y_train_states_encoded], epochs=5,
             validation_data=(X_test_scaled, [y_test_symptoms, y_test_states_encoded]),
             callbacks=[early_stopping])

Epoch 1/5
380606/380606 [==============================] - 607s 2ms/step - loss: 0.8733 - symptom_output_loss: 1.0324 - state_output_loss: 0.7142 - symptom_output_mae: 1.0324 - symptom_output_accuracy: 0.3918 - state_output_mae: 1.0641 - state_output_accuracy: 0.6951 - val_loss: 0.8342 - val_symptom_output_loss: 0.9860 - val_state_output_loss: 0.6819 - val_symptom_output_mae: 0.9860 - val_symptom_output_accuracy: 0.4020 - val_state_output_mae: 1.0641 - val_state_output_accuracy: 0.7086ut_loss: 0.7881 - symptom_output_mae: 1.1446 - symptom_output_accuracy: 0.3298 - state_output_mae: 1.0617 - state_output_ - ETA: 8:05 - loss: 0.9636 - symptom_output_loss: 1.1413 - state_output_loss: 0.7858 - symptom_output_mae: 1.1413 - symptom_output_accuracy: 0.3316 - state_output_mae: 1.0628 - state_output_accuracy: 0 - ETA: 8:05 - loss: 0.9627 - symptom_output_loss: 1.1403 - state_output_loss: 0.7851 - symptom_o - ETA: 7:49 - loss: 0.9330 - symptom_output_loss: 1.1026 - state_output_loss: 0.7634 - sy

In [24]:
y_pred_states = one_head.predict(X_test_scaled)
y_pred_states

[array([[ 2.0794389e+00,  3.7943709e-01,  1.2750665e+00, ...,
          4.6907916e+00,  2.6193215e-04, -1.2302357e-02],
        [ 2.0382905e+00,  4.1285300e-01,  1.3822848e+00, ...,
          4.7160530e+00,  8.5518789e-03, -2.0635545e-02],
        [ 1.9281644e+00, -4.0660501e-02,  1.3778751e+00, ...,
          4.2531075e+00,  6.7975065e-03, -4.2829543e-02],
        ...,
        [ 1.9830754e+00,  1.9953948e+00,  4.7922888e+00, ...,
          2.0286169e+00,  9.4896397e-03,  1.0232629e+00],
        [ 1.9830754e+00,  1.9953948e+00,  4.7922888e+00, ...,
          2.0286169e+00,  9.4896397e-03,  1.0232629e+00],
        [ 1.9830754e+00,  1.9953948e+00,  4.7922888e+00, ...,
          2.0286169e+00,  9.4896397e-03,  1.0232629e+00]], dtype=float32),
 array([[7.8032598e-02, 2.5640377e-01, 2.9011501e-03, 6.6266251e-01],
        [8.0085419e-02, 2.3500259e-01, 4.0035588e-03, 6.8090850e-01],
        [3.1583171e-02, 3.4477609e-01, 5.0024758e-04, 6.2314057e-01],
        ...,
        [9.9672037e-01, 8.3

In [25]:
y_pred_states = np.argmax(y_pred_states[1][:], axis=1)
y_pred_states

array([3, 3, 3, ..., 0, 0, 0], dtype=int64)

In [26]:
print(confusion_matrix(y_test_states_encoded, y_pred_states))

[[1386143  306652       0   38844]
 [ 150720  882782       0  183039]
 [  73392    7395       0    1445]
 [  72491  334010       0  622867]]


In [27]:
print(classification_report(y_test_states_encoded, y_pred_states))

C:\Users\PRECISION 7X10\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\PRECISION 7X10\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

           0       0.82      0.80      0.81   1731639
           1       0.58      0.73      0.64   1216541
           2       0.00      0.00      0.00     82232
           3       0.74      0.61      0.66   1029368

    accuracy                           0.71   4059780
   macro avg       0.53      0.53      0.53   4059780
weighted avg       0.71      0.71      0.71   4059780



C:\Users\PRECISION 7X10\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [28]:
import shap

In [29]:
X_train_summary = shap.sample(X_train_scaled, 100)

In [30]:
X_train_scaled[1:len(X_train_scaled):1000,].shape

(12180, 86)

## explanations in term of states

In [31]:
def f(X):
    return one_head.predict(X)[1]# with this function we select the second output of the model: vector of states 

In [32]:
X_train_summary = shap.sample(X_train_scaled, 100)
explainer = shap.KernelExplainer(f, X_train_summary) 

In [33]:
#shap_sample = shap.sample(X_test_scaled, 1000)

In [34]:
end = len(X_test_scaled)
shap_values = explainer.shap_values(X_test_scaled[1:end:1000, : ]) #TO OLGA=> I've run the code on the first 10 samples. You should run it on the whole X_test_scaled

  0%|          | 0/4060 [00:00<?, ?it/s]

In [35]:
feature_names=X_test.columns
#feature_names

In [36]:
classes_names_states=list(set(le.inverse_transform(y_test_states_encoded)))
#classes_names

In [37]:
#I'm plotting the global explanation for all classes, varying the number of features to share
for max_features in [20, 40, 86]: 
  shap.summary_plot(shap_values, X_test_scaled[1:end:1000,:], plot_type="bar", class_names= classes_names_states,
                    feature_names = feature_names, max_display=max_features , show=False)
  plt.gcf()
  figname=graphsStreamPath+model_name+'_global_allclasses_states_'+str(max_features)+'.png'
  plt.savefig(figname,dpi=150, bbox_inches='tight')
  plt.clf()

<Figure size 576x2584.8 with 0 Axes>

In [38]:
#I'm plotting the global explanations for all the classes, varying the number of features to show
#I'm iterating on the number of classes (numerical)
for class_id in range(len(shap_values)):
  #I'm iterating on the number of features I want to plot
  for max_features in [20, 40, 86]: 
    shap.summary_plot(shap_values[class_id], X_test_scaled[1:end:1000,:], feature_names = feature_names, max_display=max_features,show=False)
    plt.gcf()
    figname=graphsStreamPath+model_name+'_global_class'+str(class_id)+'_features'+ str(max_features)+'.png'
    plt.savefig(figname,dpi=150, bbox_inches='tight')
    plt.clf()

<Figure size 576x2584.8 with 0 Axes>

In [39]:
shap_values_0_df = pd.DataFrame(shap_values[0], columns = feature_names)
shap_values_1_df = pd.DataFrame(shap_values[1], columns = feature_names)
shap_values_2_df = pd.DataFrame(shap_values[2], columns = feature_names)
shap_values_3_df = pd.DataFrame(shap_values[3], columns = feature_names)

shap_values_0_df.to_csv(shapvaluesStreamPath + "/shap_values_class_0_onehead_states.csv", index=False)
shap_values_1_df.to_csv(shapvaluesStreamPath + "/shap_values_class_1_onehead_states.csv", index=False)
shap_values_2_df.to_csv(shapvaluesStreamPath + "/shap_values_class_2_onehead_states.csv", index=False)
shap_values_3_df.to_csv(shapvaluesStreamPath + "/shap_values_class_3_onehead_states.csv", index=False)

In [40]:
#These are the same as before
data_shap_df=pd.DataFrame(X_test_scaled[1:end:1000,:], columns = feature_names)
data_shap_df.to_csv(shapvaluesStreamPath + "/data_shap_onehead.csv", index=False)


#X_train_summary_df=pd.DataFrame(X_train_summary, columns = feature_names)
#X_train_summary_df.to_csv(shapvaluesStreamPath + "/X_train_summary_shap_baseline.csv", index=False)

In [41]:
#columns_tocsv = ['hamd_ymrs', 'patient_id', 'hamd_suma', 'yms_suma']
df_test_shap = df_test[['hamd_ymrs', 'patient_id', 'hamd_suma', 'yms_suma']]
df_test_shap = df_test_shap[1:end:1000]
#print(df_test.columns.tolist())

In [42]:
data_shap_y = y_test_states[1:end:1000,]
data_shap_y.to_csv(shapvaluesStreamPath + "/y_shap_onehead.csv", index=False)
df_test_shap.to_csv(shapvaluesStreamPath + "/dftest_shap_onehead.csv", index=False)

## Explanations in terms of symptoms

In [72]:
def f(X):
    return one_head.predict(X)[0]# with this function we select the second output of the model: vector of states 

In [73]:
X_train_summary = shap.sample(X_train_scaled, 100)
explainer = shap.KernelExplainer(f, X_train_summary)

In [75]:
end = len(X_test_scaled)

In [76]:
shap_values = explainer.shap_values(X_test_scaled[1:end:1000,:]) #TO OLGA=> I've run the code on the first 10 samples. You should run it on the whole X_test_scaled

  0%|          | 0/4060 [00:00<?, ?it/s]

In [77]:
classes_names=y_test_symptoms.columns

In [78]:
max_features=20

In [79]:
#I'm plotting the global summary for all the classes, only for 20 features
shap.summary_plot(shap_values, X_test_scaled[1:end:1000,:], plot_type="bar", 
                  class_names= classes_names, max_display=max_features, feature_names = feature_names,show=False)
plt.gcf()
figname=graphsStreamPath+model_name+'_global_allclasses.png'
plt.savefig(figname,dpi=150, bbox_inches='tight')
plt.clf()

<Figure size 576x684 with 0 Axes>

In [80]:
max_features

20

In [81]:
X_test_scaled[1:end:1000,:].shape

(4060, 86)

In [82]:
range(classes_names.shape[0])

range(0, 10)

In [83]:
shap_values[3]


array([[-0.2827476 , -2.97626598,  0.        , ...,  0.        ,
         0.28475306, -2.10887113],
       [-0.16167605,  0.98242195,  0.        , ...,  0.        ,
         0.        , -1.25598622],
       [-0.11377993,  1.45603333,  0.02956179, ...,  0.        ,
        -0.06131176, -1.95515146],
       ...,
       [ 0.        , -0.23359007,  0.107893  , ..., -0.06405894,
         0.        , -0.94153197],
       [ 0.06971763,  0.22764732,  0.06602414, ..., -0.16694878,
         0.0686244 , -0.53091973],
       [-0.09341052,  1.06657042, -0.17708962, ...,  0.06538637,
        -0.15466056, -1.18868992]])

In [84]:
for x in range(classes_names.shape[0]):
  classes_names[x]
  shap.summary_plot(shap_values[x], X_test_scaled[1:end:1000,:], feature_names = feature_names,
                    max_display=max_features,show=False) #you can change the maximum features to display 
  plt.gcf()
  figname=graphsStreamPath+model_name+'_global_allclasses_'+classes_names[x]+'.png'
  plt.savefig(figname,dpi=150, bbox_inches='tight')
  plt.clf()

<Figure size 576x684 with 0 Axes>

In [85]:
shap_values[9]

array([[ 0.        ,  0.25376444,  0.        , ...,  0.        ,
         0.        , -0.17737026],
       [-0.00821234, -0.07254943, -0.01819041, ...,  0.        ,
         0.00533986, -0.15826038],
       [ 0.        , -0.11129415, -0.01806232, ...,  0.        ,
         0.01075979, -0.02722846],
       ...,
       [-0.00943127,  0.04337706, -0.02286818, ...,  0.        ,
         0.00745969,  0.06599261],
       [-0.0187422 ,  0.        , -0.0348451 , ..., -0.00923454,
         0.        ,  0.10096717],
       [-0.01044969, -0.11159544, -0.04194837, ...,  0.        ,
         0.0214812 ,  0.06034724]])

In [86]:
shap_values_0_df = pd.DataFrame(shap_values[0], columns = feature_names)
shap_values_1_df = pd.DataFrame(shap_values[1], columns = feature_names)
shap_values_2_df = pd.DataFrame(shap_values[2], columns = feature_names)
shap_values_3_df = pd.DataFrame(shap_values[3], columns = feature_names)
shap_values_4_df = pd.DataFrame(shap_values[4], columns = feature_names)
shap_values_5_df = pd.DataFrame(shap_values[5], columns = feature_names)
shap_values_6_df = pd.DataFrame(shap_values[6], columns = feature_names)
shap_values_7_df = pd.DataFrame(shap_values[7], columns = feature_names)
shap_values_8_df = pd.DataFrame(shap_values[8], columns = feature_names)
shap_values_9_df = pd.DataFrame(shap_values[9], columns = feature_names)

shap_values_0_df.to_csv(shapvaluesStreamPath + "/shap_values_class_0_onehead_symptoms.csv", index=False)
shap_values_1_df.to_csv(shapvaluesStreamPath + "/shap_values_class_1_onehead_symptoms.csv", index=False)
shap_values_2_df.to_csv(shapvaluesStreamPath + "/shap_values_class_2_onehead_symptoms.csv", index=False)
shap_values_3_df.to_csv(shapvaluesStreamPath + "/shap_values_class_3_onehead_symptoms.csv", index=False)
shap_values_4_df.to_csv(shapvaluesStreamPath + "/shap_values_class_4_onehead_symptoms.csv", index=False)
shap_values_5_df.to_csv(shapvaluesStreamPath + "/shap_values_class_5_onehead_symptoms.csv", index=False)
shap_values_6_df.to_csv(shapvaluesStreamPath + "/shap_values_class_6_onehead_symptoms.csv", index=False)
shap_values_7_df.to_csv(shapvaluesStreamPath + "/shap_values_class_7_onehead_symptoms.csv", index=False)
shap_values_8_df.to_csv(shapvaluesStreamPath + "/shap_values_class_8_onehead_symptoms.csv", index=False)
shap_values_9_df.to_csv(shapvaluesStreamPath + "/shap_values_class_9_onehead_symptoms.csv", index=False)
